auth_enabled: false

server:
  http_listen_port: 3100
  http_listen_address: 0.0.0.0
  
common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory   # ✅ penting, biar gak coba connect ke consul/etcd

ingester:
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  chunk_target_size: 1048576
  max_chunk_age: 1h
  wal:
    dir: /wal

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
  filesystem:
    directory: /tmp/loki/chunks

schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m

limits_config:
  allow_structured_metadata: false
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_cache_freshness_per_query: 10m
