global:
  scrape_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "kong"
    static_configs:
      - targets: ["kong:8100"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
